### ISSUE TITLE
Swap out pyorc and use pyarrow instead

### ISSUE THREAD

**Issue by iajoiner** [lowes/lvfs#6]
PyArrow 4.0.1+ has both the ORC reader and the ORC writer. Moreover it does not have conflict with Tensorflow. Let's use PyArrow for our ORC I/O needs from now on.

**Comment by sean-gallagher-redvest** [comment]
Looks like you're in progress with this, under PR #11

**Comment by iajoiner** [comment]
Resolved by PR #11
